---
notifications:
  email:
  - team@appwrite.io
  
services:
- docker

install:
- docker-compose up -d
- sleep 30

script:
- docker ps -a
- docker-compose logs clamav
- >
  if : >/dev/tcp/localhost/3310; then
    echo 'Connection available.'
    exit 0
  else
    echo 'Connection unavailable.'
    exit 1
  fi
